elasticsearch:
  image: elastic-pi:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
    - /opt/elastic/config/:/usr/share/elasticsearch/config
    - /opt/elastic/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  image: kibana-pi:latest
  volumes:
    - /opt/kibana/config/:/opt/kibana/config
    - /opt/kibana/config/:/opt/kibana/plugins
  ports:
    - "5601:5601"
  links:
    - elasticsearch

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch